### ISSUE TITLE
(Rust) Parameter type &Vec<f64> can lead to unnecessary copies

### ISSUE THREAD

**Issue by mherrerarendon** [msimms/PeakFinder#1]
[This](https://github.com/msimms/PeakFinder/blob/main/rust/src/peaks.rs#L203) function (and any others that take a reference to a vector) could take a &[f64] instead of a reference to a vector.
In my use case, I start out with a `&[f64]`, so this function signature forces me to copy my slice into a new `Vec<f64>`.
Fortunately, because of Rust magic, changing the parameter type from `&Vec<f64>` to `&[f64]` is a non-breaking change.

I'd be happy create a PR, if you agree with this change.

**Comment by msimms** [comment]
Sounds good. Still getting the hang of Rust myself.

**Comment by mherrerarendon** [comment]
I ran the tests and they passed, so https://github.com/msimms/PeakFinder/pull/2 should be good to merge if you agree with the change.

**Comment by mherrerarendon** [comment]
Hi @msimms ,
Would it be possible for you to publish a new version of this Rust library (crates.io) that includes this PR?

**Comment by msimms** [comment]
Sure. I'll do that!

**Comment by msimms** [comment]
Done

**Comment by mherrerarendon** [comment]
Excellent, thank you!
